analyzer:
  errors:
    constant_identifier_names: ignore
    no_leading_underscores_for_local_identifiers: ignore
    non_constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable these rules to get warnings about missing const
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true