// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnx3ezDy3Wkv_jYpt17rAJsez0_pUFiXU',
    appId: '1:567685771459:web:1ecba0e514b103f8e97276',
    messagingSenderId: '567685771459',
    projectId: 'atlas-manhwa',
    authDomain: 'atlas-manhwa.firebaseapp.com',
    storageBucket: 'atlas-manhwa.firebasestorage.app',
    measurementId: 'G-TVRCPBXSTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD056aj9o-aDSQOdW2xU5sLzrwdghykO6A',
    appId: '1:567685771459:android:44f410d3f2be051de97276',
    messagingSenderId: '567685771459',
    projectId: 'atlas-manhwa',
    storageBucket: 'atlas-manhwa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQaq-4rMHxc_N8lSTPjrmG55WNNRixUg',
    appId: '1:567685771459:ios:24c2c78b0306aa92e97276',
    messagingSenderId: '567685771459',
    projectId: 'atlas-manhwa',
    storageBucket: 'atlas-manhwa.firebasestorage.app',
    iosBundleId: 'com.example.atlasApp',
  );
}
